server:
  port: ${PORT:8084}

spring:
  application:
    name: user-service

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/user_service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Krishnal@21}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:romeokanhai@gmail.com}
    password: ${MAIL_PASSWORD:ilgo tooj uqzf rhte}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${HOSTNAME:localhost}
    preferIpAddress: true

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: 86400000
  refreshExpiration: 604800000

verification-url: ${VERIFICATION_URL:http://localhost:8084/api/auth/verify}
