server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: 86400000
  refreshExpiration: 604800000

spring:
  application:
    name: getway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/users/**

        - id: question-service
          uri: lb://question-sheet
          predicates:
            - Path=/api/questions/**

        - id: resume-service
          uri: lb://resume-service
          predicates:
            - Path=/api/resume/**

        - id: roadmap-service
          uri: lb://roadmap-service
          predicates:
            - Path=/api/roadmap/**

        - id: gen-service
          uri: lb://gen-service
          predicates:
            - Path=/api/gen/**,/api/gemini/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${HOSTNAME:localhost}
    preferIpAddress: true
